[package]
name = "pingussy"
version = "0.1.0"
authors = ["Blexyel <passihd@pingusmc.org>"]
edition = "2018"

[dependencies]
hocon = "0.9.0"
lazy_static = "1.4.0"
serde = "1.0.196"
serenity = "0.12.0"
tokio = "1.36.0"
